// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVyXbabnlPXy3AXHVehTyzjEM6qKeTxKU',
    appId: '1:34749539565:web:787bcab0c5b58d657718e4',
    messagingSenderId: '34749539565',
    projectId: 'video-downloader-b218a',
    authDomain: 'video-downloader-b218a.firebaseapp.com',
    storageBucket: 'video-downloader-b218a.firebasestorage.app',
    measurementId: 'G-0DGXX7N1CJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5OCEpV0DXV8h50UqD2EHVPkpLHzKEleE',
    appId: '1:34749539565:android:09ccd527fc60405f7718e4',
    messagingSenderId: '34749539565',
    projectId: 'video-downloader-b218a',
    storageBucket: 'video-downloader-b218a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwyqNeCNRhbHP6D7RitFKWArqzgDulSw4',
    appId: '1:34749539565:ios:f1421b629aebe16b7718e4',
    messagingSenderId: '34749539565',
    projectId: 'video-downloader-b218a',
    storageBucket: 'video-downloader-b218a.firebasestorage.app',
    iosBundleId: 'com.ibrar.videoDownloader',
  );
}
